version: "3.9"

services:
  bot:
    container_name: get_anime_bot.bot
    restart: "unless-stopped"
    env_file:
      - ".env"
    build:
      context: .
      dockerfile: "Dockerfile"
    networks:
      - get_anime_bot.postgres.network
    depends_on:
      postgres:
        condition: service_healthy
    profiles: ["prod"]
  
  bot-dev:
    container_name: get_anime_bot.bot.dev
    restart: "unless-stopped"
    env_file:
      - ".env"
    build:
      context: .
      dockerfile: "Dockerfile.dev"
  
    networks:
      - get_anime_bot.postgres.network
    depends_on:
      postgres:
        condition: service_healthy
    profiles: ["dev"]

  postgres:
    container_name: get_anime_bot.postgres
    image: "postgres:15-alpine"
    hostname: get_anime_bot.postgres
    restart: "unless-stopped"
    expose:
      - "5432"
    ports:
      - "127.0.0.1:${POSTGRES_PORT:-5432}:5432"
    networks:
      - get_anime_bot.postgres.network
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_USER: ${POSTGRES_USER:-$USER}
      POSTGRES_DB: ${POSTGRES_DB:-$USER}
    volumes:
      - get_anime_bot.postgres.data:/var/lib/postgresql/users:rw
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 60s
      retries: 5
      start_period: 10s

volumes:
  get_anime_bot.postgres.data: {}

networks:
  get_anime_bot.postgres.network: {}
